name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget. (MB version)
version: 2.0.0-mb.1
homepage: https://github.com/martin-braun/google_maps_place_picker_mb

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.1
  geolocator: ^7.0.1
  permission_handler: ^6.0.1+1
  provider: ^5.0.0
  google_maps_webservice: ^0.0.20-nullsafety.2
  google_api_headers: ^1.0.0
  tuple: ^2.0.0-nullsafety.0
  http: ^0.13.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
